# Generated by Django 3.1.5 on 2021-02-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок новости')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновления')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публиковать')),
            ],
        ),
    ]
